//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonocapital
    {
        public abonocapital()
        {
            this.backup_cuota = new HashSet<backup_cuota>();
        }
    
        public int AbonoCapitalId { get; set; }
        public int CreditoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Observacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> AbonoCapitalNro { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public bool Estado { get; set; }
    
        public virtual credito credito { get; set; }
        public virtual ICollection<backup_cuota> backup_cuota { get; set; }
    }
}
