//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnetroles
    {
        public aspnetroles()
        {
            this.aspnetusers = new HashSet<aspnetusers>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<aspnetusers> aspnetusers { get; set; }
    }
}
