//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backup_cuota
    {
        public int BackupCuotaId { get; set; }
        public int AbonoCapitalId { get; set; }
        public int CuotaId { get; set; }
        public int CreditoId { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> AbonoCapital { get; set; }
        public Nullable<decimal> AbonoInteres { get; set; }
        public Nullable<decimal> AjusteAbonoCapital { get; set; }
        public Nullable<decimal> AjusteAbonoInteres { get; set; }
        public Nullable<decimal> SaldoCapital { get; set; }
        public Nullable<decimal> SaldoInteres { get; set; }
    
        public virtual abonocapital abonocapital1 { get; set; }
    }
}
