//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivo
    {
        public int EmpresaId { get; set; }
        public Nullable<int> CreditoNro { get; set; }
        public Nullable<int> RetiroInteresNro { get; set; }
        public Nullable<int> AbonoNro { get; set; }
        public Nullable<int> AbonoCapitalNro { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
