//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class divisioncredito
    {
        public divisioncredito()
        {
            this.credito = new HashSet<credito>();
        }
    
        public int DivisionCreditoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<credito> credito { get; set; }
    }
}
