//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class icreditEntities : DbContext
    {
        public icreditEntities()
            : base("name=icreditEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<abono> abono { get; set; }
        public virtual DbSet<abonocapital> abonocapital { get; set; }
        public virtual DbSet<aporte> aporte { get; set; }
        public virtual DbSet<aspnetroles> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaims> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogins> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetusers> aspnetusers { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<conceptoaporte> conceptoaporte { get; set; }
        public virtual DbSet<conceptoretiro> conceptoretiro { get; set; }
        public virtual DbSet<consecutivo> consecutivo { get; set; }
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<cuota> cuota { get; set; }
        public virtual DbSet<divisioncredito> divisioncredito { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<loghome> loghome { get; set; }
        public virtual DbSet<paramcorreo> paramcorreo { get; set; }
        public virtual DbSet<retiro> retiro { get; set; }
        public virtual DbSet<retirointeres> retirointeres { get; set; }
        public virtual DbSet<socio> socio { get; set; }
        public virtual DbSet<tipocuota> tipocuota { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<credito> credito { get; set; }
        public virtual DbSet<backup_cuota> backup_cuota { get; set; }
    }
}
