//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrediAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class retiro
    {
        public int RetiroId { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public System.DateTime Fecha { get; set; }
        public int SocioId { get; set; }
        public int ConceptoRetiroId { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual conceptoretiro conceptoretiro { get; set; }
        public virtual socio socio { get; set; }
    }
}
